### ISSUE TITLE
Breaks on symlinks

### ISSUE THREAD

**Issue by OmgImAlexis** [hcodes/yaspeller#128]
```shell
➜  webgui git:(master) yaspeller -e ".md,.html,.js,.php,.page" ./plugins/dynamix/                  
Spelling check:
fs.js:126
    throw err;
    ^

Error: ENOENT: no such file or directory, stat '/Users/xo/code/limetech/webgui/plugins/dynamix/images/case-model.png'
    at Object.statSync (fs.js:856:3)
    at Object.isDir (/usr/local/lib/node_modules/yaspeller/lib/utils.js:18:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/yaspeller/lib/utils.js:71:30)
    at Array.forEach (<anonymous>)
    at find (/usr/local/lib/node_modules/yaspeller/lib/utils.js:68:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/yaspeller/lib/utils.js:72:25)
    at Array.forEach (<anonymous>)
    at find (/usr/local/lib/node_modules/yaspeller/lib/utils.js:68:34)
    at Object.findFiles (/usr/local/lib/node_modules/yaspeller/lib/utils.js:81:13)
    at Object.forFiles (/usr/local/lib/node_modules/yaspeller/lib/tasks.js:128:18) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/Users/xo/code/limetech/webgui/plugins/dynamix/images/case-model.png'
}
```

The file does exist.
```shell
➜  webgui git:(master) ls -lah /Users/xo/code/limetech/webgui/plugins/dynamix/images/case-model.png
lrwxr-xr-x  1 xo  staff    43B  7 Jan 15:54 /Users/xo/code/limetech/webgui/plugins/dynamix/images/case-model.png -> /boot/config/plugins/dynamix/case-model.png
```

**Comment by hcodes** [comment]
Thanks!
v6.1.0
