### ISSUE TITLE
code does not work

### ISSUE THREAD

**Issue by alexdruk** [hcodes/yaspeller#157]
yaspeller -e .html --ignore-urls http://localhost/sitemap.xml
/Users/alex/.nvm/versions/node/v8.1.2/lib/node_modules/yaspeller/node_modules/chalk/source/index.js:106
	...styles,
	^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/alex/.nvm/versions/node/v8.1.2/lib/node_modules/yaspeller/lib/cli/index.js:4:15)

**Comment by hcodes** [comment]
https://github.com/hcodes/yaspeller/blob/master/package.json#L60
Node.js >= 10
