### ISSUE TITLE
Error: socket hang up, callback was already called

### ISSUE THREAD

**Issue by M1troll** [hcodes/yaspeller#192]
Hi!

When using a VPN, sometimes a `Socket hang up` error occurs.
Can you add a more informative error message for this situation?

Traceback:
```bash
Spelling check:
Error: socket hang up
Error: socket hang up
/home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/node_modules/async/dist/async.js:324
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at /home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/node_modules/async/dist/async.js:324:36
    at /home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/node_modules/async/dist/async.js:3679:17
    at /home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/lib/yaspeller.js:98:21
    at /home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/node_modules/yandex-speller/lib/yandex-speller.js:38:13
    at callbackMock (/home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/node_modules/yandex-speller/lib/post.js:76:24)
    at ClientRequest.<anonymous> (/home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/node_modules/yandex-speller/lib/post.js:50:9)
    at ClientRequest.emit (node:events:514:28)
    at Socket.socketCloseListener (node:_http_client:468:11)
    at Socket.emit (node:events:526:35)
    at TCP.<anonymous> (node:net:337:12)

Node.js v20.8.0
Spelling check:
Error: socket hang up
Error: socket hang up
/home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/node_modules/async/dist/async.js:324
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at /home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/node_modules/async/dist/async.js:324:36
    at /home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/node_modules/async/dist/async.js:3679:17
    at /home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/lib/yaspeller.js:98:21
    at /home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/node_modules/yandex-speller/lib/yandex-speller.js:38:13
    at callbackMock (/home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/node_modules/yandex-speller/lib/post.js:76:24)
    at ClientRequest.<anonymous> (/home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/node_modules/yandex-speller/lib/post.js:50:9)
    at ClientRequest.emit (node:events:514:28)
    at Socket.socketCloseListener (node:_http_client:468:11)
    at Socket.emit (node:events:526:35)
    at TCP.<anonymous> (node:net:337:12)

Node.js v20.8.0
Spelling check:
Error: socket hang up
Error: socket hang up
/home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/node_modules/async/dist/async.js:324
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at /home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/node_modules/async/dist/async.js:324:36
    at /home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/node_modules/async/dist/async.js:3679:17
    at /home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/lib/yaspeller.js:98:21
    at /home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/node_modules/yandex-speller/lib/yandex-speller.js:38:13
    at callbackMock (/home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/node_modules/yandex-speller/lib/post.js:76:24)
    at ClientRequest.<anonymous> (/home/anton/.cache/pre-commit/repoj5akw5ba/node_env-default/lib/node_modules/yaspeller/node_modules/yandex-speller/lib/post.js:50:9)
    at ClientRequest.emit (node:events:514:28)
    at Socket.socketCloseListener (node:_http_client:468:11)
    at Socket.emit (node:events:526:35)
    at TCP.<anonymous> (node:net:337:12)

Node.js v20.8.0
Spelling check:
Error: socket hang up
Error: socket hang up
```

**Comment by hcodes** [comment]
v9.1.0
