### ISSUE TITLE
Crash of Yaspeller when try Habrahabr url

### ISSUE THREAD

**Issue by coderaiser** [hcodes/yaspeller#22]
When I try to use yaspeller with `Habrahabr` crash occurred.
```js
node_modules/.bin/yaspeller http://habrahabr.ru

/home/coderaiser/cloudcmd/node_modules/yaspeller/node_modules/request/node_modules/qs/lib/stringify.js:30
        return [encodeURIComponent(prefix) + '=' + encodeURIComponent(obj)];
                                                   ^
URIError: URI malformed
    at encodeURIComponent (native)
    at Object.internals.stringify (/home/coderaiser/cloudcmd/node_modules/yaspeller/node_modules/request/node_modules/qs/lib/stringify.js:30:52)
    at Object.module.exports [as stringify] (/home/coderaiser/cloudcmd/node_modules/yaspeller/node_modules/request/node_modules/qs/lib/stringify.js:73:38)
    at Request.form (/home/coderaiser/cloudcmd/node_modules/yaspeller/node_modules/request/request.js:1338:81)
    at Request.init (/home/coderaiser/cloudcmd/node_modules/yaspeller/node_modules/request/request.js:456:10)
    at new Request (/home/coderaiser/cloudcmd/node_modules/yaspeller/node_modules/request/request.js:264:8)
    at request (/home/coderaiser/cloudcmd/node_modules/yaspeller/node_modules/request/index.js:50:10)
    at Function.request.post (/home/coderaiser/cloudcmd/node_modules/yaspeller/node_modules/request/index.js:80:27)
    at /home/coderaiser/cloudcmd/node_modules/yaspeller/lib/yaspeller.js:177:21
    at /home/coderaiser/cloudcmd/node_modules/yaspeller/node_modules/async/lib/async.js:570:21

node_modules/.bin/yaspeller --version
1.0.2
```

**Comment by hcodes** [comment]
Thanx, fixed.
