### ISSUE TITLE
Синтаксическая ошибка в регулярном выражении

### ISSUE THREAD

**Issue by mkpankov** [hcodes/yaspeller#83]
```
± % ➜  yaspeller community-projects.md
/home/mkpankov/.nvm/versions/node/v6.9.5/lib/node_modules/yaspeller/lib/yaspeller.js:335
        text.replace(new RegExp(item.word + '(?:' + letters + '|$)', 'g'), function($0, index) {
                     ^

SyntaxError: Invalid regular expression: /Проекты представлены в алфавитном порядке ников авторов. @blackbeam crc16 - реализация CRC16 marc - библиотека для чтения и создания библиографии в формате MARC 21 mysql - клиентская библиотека MySQL named-pipe - обёртка для асинхронного ввода-вывода в именованные каналы Windows rabbit - реализация Rabbit Stream Cipher Algorithm с поддержкой окружения без стандартной библиотеки (no_std) @defuz onig - обёртка для библиотеки регулярных выражений oniguruma, поддерживающей различные кодировки weakjson - библиотека для разбора нестандартного JSON, который вы можете встретить на просторах интернета @kstep cronparse - парсер файлов crontab kernlog - реализация низкоуровневого журналирования в mpd - клиентская библиотека для MPD (music player daemon) pb - клиент REST API сервиса PUSH-уведомлений Pushbullet vkrs - клиент API ВКонтакте …и другие @mkpankov bread - библиотека для форматированного вывода в терминал (цвет, стиль и т. д.), принимающая разметку прямо в выводимой строке @netvl ejdb.rs - обёртка для EJDB, встраиваемой базе данных на JSON immeta - библиотека разбора метаданных изображений mpfr.rs - высокоуровневая обёртка для MPFR, библиотеки для вычислений с произвольной точностью xml-rs - библиотека для работы с XML, полностью на Rust @ozkriff Zone of Control - пошаговая стратегическая игра (проект заморожен) Zemeroth - еще одна пошаговая стратегическая игра @SCareAngel functional - типажи для реализации функционального программирования на Rust (привет, монады!) future - разделяемый асинхронный результат вычислений (continuation, похоже на std: future из C++) pixel - библиотека для конвертации и смешивания (blending) цветов @Vinatorul clap - библиотека разбора аргументов командной строки @zummenix expectest - библиотека для реализации модульных тестов на Rust(?:[^a-zA-Zа-яА-ЯЁёҐґЄєІіЇї]|$)/: Nothing to repeat
    at RegExp (native)
    at /home/mkpankov/.nvm/versions/node/v6.9.5/lib/node_modules/yaspeller/lib/yaspeller.js:335:22
    at Array.forEach (native)
    at Object.addPositions (/home/mkpankov/.nvm/versions/node/v6.9.5/lib/node_modules/yaspeller/lib/yaspeller.js:331:10)
    at onResource (/home/mkpankov/.nvm/versions/node/v6.9.5/lib/node_modules/yaspeller/lib/tasks.js:22:19)
    at yaspeller.checkFile (/home/mkpankov/.nvm/versions/node/v6.9.5/lib/node_modules/yaspeller/lib/tasks.js:140:21)
    at /home/mkpankov/.nvm/versions/node/v6.9.5/lib/node_modules/yaspeller/lib/yaspeller.js:200:21
    at /home/mkpankov/.nvm/versions/node/v6.9.5/lib/node_modules/yaspeller/lib/yaspeller.js:106:9
    at /home/mkpankov/.nvm/versions/node/v6.9.5/lib/node_modules/yaspeller/node_modules/async/dist/async.js:3861:9
    at /home/mkpankov/.nvm/versions/node/v6.9.5/lib/node_modules/yaspeller/node_modules/async/dist/async.js:421:16
```

Файл в архиве во вложении

[community-projects.md.tar.gz](https://github.com/hcodes/yaspeller/files/1443196/community-projects.md.tar.gz)

**Comment by hcodes** [comment]
Этот момент не учёл, поправлю позже.
Нужно переустановить `yaspeller` и проблема исчезнет, отголоски из #84.

**Comment by hcodes** [comment]
[v4.0.2](https://github.com/hcodes/yaspeller/releases)

P.S.: Спасибо за заведённый баг.
